import os
import cv2
import joblib
import numpy as np
from skimage.feature import hog, local_binary_pattern

# Human-friendly category display names mapping
CATEGORY_DISPLAY_NAMES = {
    "dent": "Dent",
    "scratch": "Scratch",
    "crack": "Crack",
    "glass_shatter": "Glass Shatter",
    "lamp_broken": "Lamp Broken",
    "tire_flat": "Tire Flat"
}

# Damage category icons
CATEGORY_ICONS = {
    "dent": "🚗",
    "scratch": "⚡",
    "crack": "💥",
    "glass_shatter": "🪟",
    "lamp_broken": "💡",
    "tire_flat": "🛞"
}

IMAGE_SIZE = (128, 128)


def preprocess_image_bytes(image_bytes: bytes) -> np.ndarray:
    """
    Preprocesses uploaded image bytes according to the exact notebook pipeline:
    1. Decode OpenCV image from byte array.
    2. Convert BGR to Grayscale.
    3. Resize image to IMAGE_SIZE (128, 128).
    4. Apply Gaussian Blur with (3, 3) kernel.
    5. Normalize pixel values to [0.0, 1.0] (float32).
    """
    if not image_bytes:
        raise ValueError("Image bytes array is empty.")

    nparr = np.frombuffer(image_bytes, np.uint8)
    image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    if image is None:
        raise ValueError("Unable to decode uploaded image. Please provide a valid JPG, JPEG, or PNG file.")

    image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    image_resized = cv2.resize(image_gray, IMAGE_SIZE)
    image_blurred = cv2.GaussianBlur(image_resized, (3, 3), 0)
    image_normalized = image_blurred.astype(np.float32) / 255.0

    return image_normalized


def extract_features_from_bytes(image_bytes: bytes) -> np.ndarray:
    """
    Extracts handcrafted HOG + LBP features from image bytes:
    - HOG: orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2), block_norm='L2-Hys' -> 8100 features
    - LBP: P=8, R=1, method='uniform' -> 10 histogram bins
    - Concatenated total: 8110 features
    """
    image = preprocess_image_bytes(image_bytes)

    hog_features = hog(
        image,
        orientations=9,
        pixels_per_cell=(8, 8),
        cells_per_block=(2, 2),
        block_norm="L2-Hys"
    )

    lbp = local_binary_pattern(
        (image * 255).astype(np.uint8),
        P=8,
        R=1,
        method="uniform"
    )

    lbp_histogram, _ = np.histogram(
        lbp.ravel(),
        bins=np.arange(11),
        range=(0, 10),
        density=True
    )

    features = np.concatenate([
        hog_features,
        lbp_histogram
    ])

    return features


def load_model_artifact(model_path: str = "car_damage_model.pkl"):
    """
    Loads the fitted ML model artifact generated by the notebook.
    """
    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"Model artifact '{model_path}' not found. Please ensure 'car_damage_model.pkl' is in the project directory."
        )

    artifact = joblib.load(model_path)

    if not isinstance(artifact, dict) or "pipeline" not in artifact or "category_columns" not in artifact:
        raise ValueError(
            "Invalid model artifact structure. Expected a dictionary containing 'pipeline' and 'category_columns'."
        )

    return artifact


def predict_damage(image_bytes: bytes, model_artifact: dict):
    """
    Performs calibrated high-precision multi-label inference on image bytes:
    1. Extracts 8110-D HOG+LBP features.
    2. Reshapes to (1, 8110).
    3. Transforms via StandardScaler ➔ PCA.
    4. Computes calibrated category probabilities using geometric decision distances.
    5. Applies precision thresholding to detect multi-label damage categories.
    6. Automatically estimates damage severity extent (Minor, Moderate, Severe).
    """
    pipeline = model_artifact["pipeline"]
    category_columns = model_artifact["category_columns"]
    clf = pipeline.named_steps["classifier"]

    features = extract_features_from_bytes(image_bytes)
    features_2d = features.reshape(1, -1)

    scaled_pca_x = pipeline.named_steps["pca"].transform(
        pipeline.named_steps["scaler"].transform(features_2d)
    )

    category_thresholds = {
        "dent": 0.55,
        "scratch": 0.58,
        "crack": 0.60,
        "glass_shatter": 0.65,
        "lamp_broken": 0.65,
        "tire_flat": 0.65
    }

    probabilities = {}
    decision_scores = {}
    detected_categories = []

    for i, col in enumerate(category_columns):
        est = clf.estimators_[i]
        raw_score = float(est.decision_function(scaled_pca_x)[0])
        norm_w = float(np.linalg.norm(est.coef_))
        geom_dist = raw_score / norm_w if norm_w > 0 else raw_score
        
        prob = float(1.0 / (1.0 + np.exp(-geom_dist / 1.5)))
        
        probabilities[col] = prob
        decision_scores[col] = raw_score
        
        thresh = category_thresholds.get(col, 0.60)
        if prob >= thresh:
            detected_categories.append(col)

    detected_categories.sort(key=lambda c: probabilities[c], reverse=True)

    max_prob = max(probabilities.values()) if probabilities else 0.0
    num_detected = len(detected_categories)

    if num_detected >= 3 or max_prob >= 0.82:
        auto_severity = "severe"
    elif num_detected >= 2 or max_prob >= 0.65:
        auto_severity = "moderate"
    else:
        auto_severity = "minor"

    return detected_categories, probabilities, decision_scores, auto_severity
